# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  config.vm.define "controller", primary: true do |controller|
    controller.vm.box = "precise64"
    controller.vm.network "private_network", ip: "192.168.50.101"
	controller.vm.synced_folder "./share/controller", "/share",
	  create: true
    controller.vm.network "forwarded_port", guest: 22, host: 2201
    controller.vm.network "forwarded_port", guest: 80, host: 8081
  end

  config.vm.define "managed" do |managed|
    managed.vm.box = "precise64"
    managed.vm.network "private_network", ip: "192.168.50.102"
	managed.vm.synced_folder "./share/managed", "/share",
	  create: true
    managed.vm.network "forwarded_port", guest: 22, host: 2202
    managed.vm.network "forwarded_port", guest: 80, host: 8082
  end

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.
end
